name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      # Use the official Hugging Face action to deploy to Spaces
      - name: Deploy to Hugging Face Spaces
        uses: huggingface/sync-to-spaces@latest
        with:
          source: .
          # Replace spaces_app.py with app.py
          transform: |
            if [ -f "spaces_app.py" ]; then
              cp spaces_app.py app.py
            fi
            if [ -f "requirements-spaces.txt" ]; then
              cp requirements-spaces.txt requirements.txt
            fi
            echo "HUGGINGFACE_API_TOKEN=${{ secrets.HF_TOKEN }}" > .env
          space_id: "jomasego/${{ secrets.SPACE_NAME }}"
          token: ${{ secrets.HF_TOKEN }}
          sdk: docker
          auto_rebase: true
