name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SPACE_NAME: ${{ secrets.SPACE_NAME }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Hugging Face Hub
        run: pip install huggingface_hub requests
          
      - name: Create and Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configure git
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # We don't need to create the Space - it already exists
          # Just clone the repo and update files
          echo "Using existing Space: jomasego/$SPACE_NAME"
          
          # Clone the Space repository with proper error handling
          if git clone https://$HF_TOKEN@huggingface.co/spaces/jomasego/$SPACE_NAME space-repo 2>/dev/null; then
            echo "Successfully cloned the Space repository"
          else
            echo "Failed to clone repository, but continuing with space creation via API"
            python -c "from huggingface_hub import HfApi; api = HfApi(token='$HF_TOKEN'); api.create_repo(repo_id='jomasego/$SPACE_NAME', repo_type='space', space_sdk='docker', private=False)"
            # Try cloning again after creation
            sleep 5
            git clone https://$HF_TOKEN@huggingface.co/spaces/jomasego/$SPACE_NAME space-repo
          fi
          
          # Prepare files
          cp spaces_app.py space-repo/app.py
          cp requirements-spaces.txt space-repo/requirements.txt
          cp Dockerfile space-repo/Dockerfile
          cp -r llm_assistant.py space-repo/
          cp README.md space-repo/README.md || echo "No README to copy"
          
          # Create necessary directories
          mkdir -p space-repo/static space-repo/templates
          
          # Copy directories if they exist
          if [ -d "static" ]; then
            cp -r static/* space-repo/static/ || echo "No static files to copy"
          fi
          
          if [ -d "templates" ]; then
            cp -r templates/* space-repo/templates/ || echo "No template files to copy"
          fi
          
          # Add API token to environment
          echo "HUGGINGFACE_API_TOKEN=$HF_TOKEN" > space-repo/.env
          
          # Push changes
          cd space-repo
          git add .
          git commit -m "Update from GitHub Actions: $GITHUB_SHA" || echo "No changes to commit"
          git push origin main
